# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: GITHUB_ACTOR
        server-password: GITHUB_TOKEN

    - name: Build with Maven
      run: cd ${{ github.workspace }}/demo && mvn -B package --file pom.xml

    - name: List target directory contents
      run: cd ${{ github.workspace }}/demo && dir target

    - name: Publish to GitHub Packages Apache Maven
      run: |
        cd ${{ github.workspace }}/demo
        $warFile = Get-ChildItem target\*.war | Select-Object -First 1
        if ($warFile) {
          Write-Output "Found WAR file: $($warFile.Name)"
          mvn deploy:deploy-file -Dfile=$($warFile.FullName) -DgroupId=com.fadgiras -DartifactId=demo -Dversion=0.0.1-SNAPSHOT -Dpackaging=war -DrepositoryId=github -Durl=https://maven.pkg.github.com/Fadgiras/MavenTestCI
        } else {
          Write-Error "No WAR file found in target directory"
          exit 1
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}