# This workflow will build a package using Maven and then upload the WAR as a release asset

name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      FINESS_URL: ${{ vars.FINESS_URL }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up env file
      run: |
        touch ${{ github.workspace }}/demo/.env
        echo "FINESS_URL=${{ vars.FINESS_URL }}" >> ${{ github.workspace }}/demo/.env

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Extract version from POM
      id: version
      run: |
        cd ${{ github.workspace }}/demo
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Extracted version from POM: $VERSION"

    - name: Run Maven tests
      run: cd ${{ github.workspace }}/demo && mvn -B test --file pom.xml

    - name: Build with Maven
      run: cd ${{ github.workspace }}/demo && mvn -B package --file pom.xml

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}-${{ github.run_number }}
        name: Release v${{ steps.version.outputs.VERSION }}-${{ github.run_number }}
        files: ${{ github.workspace }}/demo/warBuilder/target/test-Build.war
        draft: false
        prerelease: false